name: MAVROS Mission Tests
on:
  push:
    branches:
    - 'main'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build SITL and Run Tests (inside old ROS container)
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/workspace" \
            -w /workspace \
            px4io/px4-dev-ros-melodic:latest \
            bash -c '
              set -e
              git config --global --add safe.directory /workspace
              git config --global --add safe.directory "*"

              # 複製自訂 mavlink message 到 submodule 裡
              cp /workspace/custom_mavlink/custom_down.xml \
                /workspace/src/modules/mavlink/mavlink/message_definitions/v1.0/
              cp /workspace/custom_mavlink/custom_up.xml \
                /workspace/src/modules/mavlink/mavlink/message_definitions/v1.0/
              cp /workspace/custom_mavlink/common.xml \
                /workspace/src/modules/mavlink/mavlink/message_definitions/v1.0/

              pip2 install --upgrade "pyyaml==3.13"
              
              PX4_SBOM_DISABLE=1 make px4_sitl_default
              PX4_SBOM_DISABLE=1 make px4_sitl_default sitl_gazebo-classic


              ./test/rostest_px4_run.sh \
                mavros_posix_test_mission.test \
                mission:=MC_mission_box \
                vehicle:=iris
            '
